arch-fsl-layerscape/imma_lsch3: Add missing declaration
Copy declaration from immap_lsch2.h. Fixes the warning/error:
drivers/pci/pcie_layerscape_ep.c:279:27: error: implicit declaration of function 'get_svr' [-Wimplicit-function-declaration]

Signed-off-by: Alexander Stein <alexander.stein@ew.tq-group.com>