driver: mxc_gpio: fix mxc_gpio_plat assignment for MX6UL
If you have defined MX6 and don't use the OF_CONTROL
this assignment causes build breaks.

drivers/gpio/mxc_gpio.c:404:27: error: 'GPIO6_BASE_ADDR' undeclared here (not in a function)
  { 5, (struct gpio_regs *)GPIO6_BASE_ADDR },
                           ^
drivers/gpio/mxc_gpio.c:407:27: error: 'GPIO7_BASE_ADDR' undeclared here (not in a function)
  { 6, (struct gpio_regs *)GPIO7_BASE_ADDR },

This patch fix this.

Signed-off-by: Marco Felsch <Marco.Felsch@tq-group.com>