tools/buildman: fix for newer U-Boot versions
In order to compile with newer U-Boot, backport of commit
256126c2943 ("buildman: Replace the Options column with config name")
to prevent CI errors in the form:

AttributeError: 'NoneType' object has no attribute 'str_value'

Tested with

TQMaxx-u-boot-v2017.11 (patched)
TQMa57xx-u-boot-v2019.04
TQMaxx2-v2016.03-rel_imx_4.1.15_2.0.0_ga (patched)
TQM-lf_v2023.04

Signed-off-by: Markus Niebel <Markus.Niebel@ew.tq-group.com>